/*
 * 版权所有.(c)2008-2017. 卡尔科技工作室
 */

package com.carl.auth.shiro.client.demo.controller;

import org.pac4j.cas.client.rest.CasRestFormClient;
import org.pac4j.cas.profile.CasProfile;
import org.pac4j.cas.profile.CasRestProfile;
import org.pac4j.core.context.J2EContext;
import org.pac4j.core.credentials.TokenCredentials;
import org.pac4j.core.profile.ProfileManager;
import org.pac4j.jwt.profile.JwtGenerator;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpEntity;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.client.RestTemplate;
import org.springframework.web.util.WebUtils;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.security.Principal;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

/**
 * @author Carl
 * @date 2017/9/16
 * @since 1.0.0
 */
@Controller
public class IndexController {
    @Autowired
    private JwtGenerator generator;

    @Autowired
    private CasRestFormClient casRestFormClient;

    @Value("${cas.serviceUrl}")
    private String serviceUrl;


    @Autowired
    RestTemplate restTemplate;

    @GetMapping("/")
    public String index(HttpServletRequest request, Model model) {
        //用户详细信息
        Principal principal = request.getUserPrincipal();
        model.addAttribute("user", principal);
        //打开index.html页面
        return "index";
    }

    @GetMapping("/user/detail")
    @ResponseBody
    public Object detail(HttpServletRequest request) {
        return request.getUserPrincipal();
    }


    @RequestMapping("/user/login")
    @ResponseBody
    public Object login(HttpServletRequest request, HttpServletResponse response) {
        Map<String, Object> model = new HashMap<>();
        J2EContext context = new J2EContext(request, response);
        final ProfileManager<CasRestProfile> manager = new ProfileManager(context);
        final Optional<CasRestProfile> profile = manager.get(true);
        //获取ticket
        TokenCredentials tokenCredentials = casRestFormClient.requestServiceTicket(serviceUrl, profile.get(), context);
        //根据ticket获取用户信息
        final CasProfile casProfile = casRestFormClient.validateServiceTicket(serviceUrl, tokenCredentials, context);
        //生成jwt token
        String token = generator.generate(casProfile);
        model.put("token", token);
        //需要将token管理

        String url = "https://passport.hope.com:8443/cas/login?service=http%3A%2F%2Flocalhost%3A9090%2Fwangwu.jsp";

        String rr = com.carl.auth.shiro.client.demo.utils.WebUtils.httpsRequest(url,"GET",new HashMap<String, Object>());

        rr=rr.substring(rr.indexOf("value")+7,rr.lastIndexOf("\""));


        System.out.println("lt:"+rr);
        return new HttpEntity<>(model);
    }

    //<input type="hidden" id="cas_login_execution" name="execution" value="08d04d03-8c0d-4713-b841-2ca841976bcd_ZXlKaGJHY2lPaUpJVXpVeE1pSjkuSzI1MFYwOUhTakF2WVVGRlF6aGtjRE5OV0c4NVkwaE9OMlp5UWswMVVWUllPVlJ2UW1KcmJHSlVUVU5rVkRCMVpYRnRTR1pEZFdacUswMXBjek5FTUROVFVuaFhRMm8zY0ZSclVrOVpZMWhXZVZjd1YyRnhaWGtyZUVoSk9VaDNiRFJ1YTBkNldtTnJiekJDYUdWSFRtcG1SRGRrZEV4aWNVdGxiWHBHUTFaYWVVZzVaamRyTDBKbmEyMTJLMlJPYkZacmRFZENOVU40ZFZrMGFFOW9NaXRsVFhWVVlrcE1jR3N2ZG5OT2RFcFlVV2hUTUhkdVJHbzBiV3RQWjFwS1VtTlBlVE5rU1VoTWNWWjFiRTF3UlRFeWQzbGFZMEZ0YVRsWlVVVm9hVlpLWnpoVFJucFlTVXhNVDJ4VlFYZHVXWEl5YnpOa1FsQjZTME52TXpOaFdHcFRTM05QS3pOMVNVeHJURTVsY1ZCRmFsRmFXVlYwTTJwVmF5OXNkMFUyZWsxSmEwSnZha2xZZWpOUVprYzBibWRTYmxoNVZWZFZOREZJZG1weU5TdGlkVlJOU1hZM1NISTFZV01yUlZCMllrUTJhMXBuVWtoRFIyVnhaRWROUnpsR1EweEVMMFpGZUVKUmVscGxRMWRRSzA1bGRHVjVkamczTUhrMUwzVnhSMFpZWjJWck9YZExNa1pIZVVsaFJXazJRWFF5V0ZoRWJFWnRVWGs0UkZWTllsZDVkSEpsZERWaWIxcGFSRTVyWVNzeWJqTjFRMHM1UVhaU1RUZ3lkMEp4UkhaUFYxRk1kaXRuU2xZelRrZElSbGxuV0hGdFExWmhVMWcxUkdORlRGTlplVEpOTkRoSE5rVm5XaTlRUmtVd05sRnRWRmhWYmpCeFFXRlBlR1J2VERsRWN6QlJOMVY2YWtkbmFDdHBkVUp2UmtwcUswazVaalpEYkVabk56RjRRMlZSVm1jMWJsZGtTMjB3VTNReloyMUNXbWc1WmxkdmJWbDJSMGxKTmt4NGJVSnRlR0pyVkZCMWJVbFdjazl6UzNseFMyaHlXR1V5U0ZWdlZXSkhjbVZYYVd0a1EzbEpSbXA1WmpoV2NVZHRVVUkxV2xwS1FTODRiM1VyTjJRelptbDVUa2RpVmxabVNscHpNbVJNWVRVM2F5dE1XVXAyZUV0UVJ5OXZTRUZQSzFvd2JuTlNOblZCWTJaaGVsTlZZa1ptZUdkSGNIcENUbXBMUzBoSFRsTTRWWEJ0V2tSNk9XdFhUblZ3VTFsd2RYVkRSRzVaUjJwek5EVTRhVUZYVGxCT1JsaDZPVlZTTnk5WE1sQXpkMGRuTlZsaVpWTnVWekEwY1drM1EwTlRWbkpCUVhjd1NraEVjVEZVZUUwd01YcDVWVm9yVGtFMFdYZDVRMUZQTURSeU9UTktjamR1TDFRcmRqUlBRWEZSWjFSSGJuTjFVa2NyV1hobk5GWkpOMUZXTDFkcU9HMTBLMlpXUlZWcmQwRmhTalJCZGxCa2JHd3JiSEkyVEhGUFlYRmplbk5NYVUxSVNsVnRjVThyU2sxWk5GSlFhSFJTTmtSWlNVODJTM2xsYW5OSVNEZEVTVnBpZFVsdk5VSTFlRm95UTJONWNqZDBXWFV3YjFCNFR5dGxaeTgwT0VwUGFTOWpZbk5DU0VRNVNsWnVNWFF6U1ZvMmFGcEhSVE5OTUVzeU1qRk5TakpHY21JeFZVdDNOSGMyYWpCck1EUmxiWFUyVFdoSWNWRkJaV05hU0ZrNGQxRTRWbUpQWVVwWFdFNTFOVlJ6VGtWUk1WcFZka3RvZUdWM1UyNUNXV1U0Y1dKbWVYVnRVRE00V0RGbWIxbFZUMlZYTlRKdVVrMHpUSEpGV25sRWRsbHNiVUpwWmtWRVQzVjRNalZVT0RkUGEzZERkbVUwYTJsa1dYVmlOMkZoTVZneFJWcHBjREJuVm1wSGVUaFRkVmhVU1hOQ2MyUjBUMGR3VHpNNVJEazNWbGN5ZFZOdFJVSndWVE5OVGxKa1lsbFlSMnBDWWtObVJpdExTR0ZSV0ZGSFlXVXZLeXR4ZEN0YU9EVnVSME5RYzFOMlVuTmhja2xJWTA5bFQyMUZUM3BsUW10VFNrOVdZVE5QVGk5UU5tbDBjV000WlROV2VYSlBka0kzYWpoaE0wSnZRV0ZMZFRWbFRYTktaV0p3Y2xobVdrdFdTRFYzVDJsS1JrUlROR1kwZHpsVk4yNDBPRVZYTVdJdkszWlNiVmRNWkhCQ1pGa3lTMVp1V1dGVmF6bGtaVGxwZDBsRFduUnNSMk40YmpaWlJHcGFNblp0WjFFcmJHVkpVMjFzU201TGJGY3JSRVpXYWpoS1ZWWm9OVkI2U1RFNVIzTlZMMDQ1VHl0RldtOUlTaXRsVG5aSlJ5dHZaVUpxUzIxQk5tNVJlVnBEUlhZNGMyUk1SRmRVUmtveVZsQlNiVTFHWWpKUE5FUktWMjR4ZURrMFZrUjFlRlpDTW5CbFJGUTNVMlUzTWtkeEswbENXRlJXU1dNdk1YQkJVak5OU1ZSME5tSXJZV3hhYzB4NVZscFRabXBzVjNsb2VUUXlWRGsxYjFsRWVqaEdjSHBpZFVveU1uQmFjWEJwVHpJdmVVaGxlV0UxT1RsbUsxWnNORXhVUldKVU56VnNkR1IxZW1RMlYxRnBLMnhVVFdSc1JVSjFUV0ZwVFVoQlIyaDVWMFZGSzJzM1JHeFdaRzVzVUVFd1NWWjRWVk4wTVVOYVIzcENjWEE1VjBaNlQzUlpVSEp1TDNkNkwwWklVbXB5VkZFelYwaEhiREpoY0ZCNWRXUnpOMmxRWjA1SFNXRTBVbU5VVkdSVVIzTkhlWGx3VEVOUlptWnVNMW8zUWpWcmFqZFZha2hTV0U1eFVXdFlTV1I0TjBGTWFGVktXWFJpY21wWVdsY3lVM2wxZUZKb05VRjBaVEZ3UVhaTVJGSlhURVJqVDFoalZFNTJOelVyV1RWYVVqRXZVWEpxTWtSeE0yODVSa1Z2VDJkMFNYZ3dabmd3VTNsd1kzSllUR2hxWTFKd0sybDRVRFJTYjFWNEszVlZSMWxGTTJsTU9XaEdWbGwwWTNnek4yVTBVa2R1ZEV0WlVuVjNWazk1TVZWUmRHVmlRWGxFV1ZwTWRtVXpUMHg2VERoaVRuUlRkVmxhUkU5Sk5UWk1Ta3h0ZVV4b2NEYzBOM0ZXUTJoNVptWlBXSGN3U1RWMVl6RTFhbmxVWW05b1V5OHdjazB3TlZWd05EQTNjekpEVW5GcGJGRXpUVkpQUTFadGQzZ3hlRlJqYWxWUk5uTnZOamhEUzB4elJEVmpOblJwYjNOUGNWUXhSbEZUTTB0clNtZDNaMnBvWnpKdkwyVnplazVaZW5oQmVrbDRabEJ0TURKb1psZDZkV2ROVjBwUFZEVlNMMUJHVkhGV1JFdFZiMEpsYjJkRGRUQklka1kwWWtwVU9EbDFUMDVOZEVoTVFYWTRiV2RrTmtKemJFSnVXRXhHYmxkRksxQlBTamRQZDFGTGRYQlpWR2hMWm5sbFJYZzBla3hRZG5wcWFGWmFhMFZSUlVGc1pHRnNUVWd2ZVN0SVRXMHJTWGRYVWxwTVNUZG5WMGRFVkVSa1dWRm5VMmQ2VkhkMVJ6TlJZMWcyVTNkeFNtaEpja05zY0RCallWVktVekF4TjNoMmRWUTBZbFY2WVZwQlMyTXllU3R5VEdkM00wVnFSblVyT1VvMFNVVmFORXBCWkZSalpFaGpSa2R2WjNkUlFYVkRORFpXVWt0MFMyeEZOVXh2WW5JdlYzZzVibUZLYmtoSk1taFhlVXROTm5SdVRrTlFXblp1ZW1oUVZsRlJWVlY1WkV4WFNEVnZTMk5QYzB4bVNHcFJhemRZUkRKbE1FUk9SbmRIV1VSNllXTnFSbkZPVjJ4WFRVbGpkVTFMU25WaVZrVmxUVmR2V1RoRlZEZG9TekJUZVdvNVFsZHJOR0pvTjNjeGVtTnlLMmRNWkhWSlZFbElUelpOTkN0Q0t6Qm1kVmxhYzI5amVVRkVVME1yWTFKTWVrSjViRmxXYTJvemNHSkVhM0ZvVldOYVZIbGtPVmxqU0ZsU1pUSk9VMHN3WldkWmRsY3JSMGRzYW0xclJHRnZlRzRyZEdOQlMzQXlhRzl4U2xobWIwcGpkV00yYW5STWVEZDFVMVJ3U0VSdFZrRlJWV2RYTW5vMFYwTjFSUzh4TVhaQk4wVnJUMU5MVkRaUFFVVndTWEZOV25OQlNuZHdWRE5yY0U1aU9UWnljMnhYTkV0S1dsTk9kbGxoWTNsTk9FTk1aRlk1UzBKUGNrWk1hREYxV0VsUVNrNVNNVFZhVkZkeFNqQlZNbWg1U0RCSmRqaElRVXhPVUVseGRtZENRbE5EU0RKa1EwNUtkVUY1TVVKUEswczNSREJhWTJWVFNGZDVla0ZXVlM5eFNsVnFVa1I2Tm5reWMwd3JXV3RMVERsdEwyRXpXbTlDVW5ZMlNuTkJSSGxKYVZsR1pHbFdNbmhYVTFaeVNWUXhhVGhHYXpoMVp6bFVUMWMxUzJwdmRFWkNVbXhMTWtOUlZsVndjekZXVFZVM0wyRkRRek1yTVdseGVGQXlOamhSY1cxUFdtRnNRVFZhY0VWbmJFeGtNVnB0TWpsdWVqaEljR1Y1TjJsMk5YTmpNM05YTTJvMldVWkpla05ZUjJ0RmRHWkZWamxqYVhRdlJETXhjQzlwVG1KSE1FeDBOV1ZxVEhkbU5sUXdhRmhMYUdKNldWWXZZM0YwUzJOellqSnRlbmR4T1ROT1dWQTRiRzFuYmpGd2FEaERkMHhFZDNkNVUyRm9hRWhKWkhsd1FqaHZRV052TUhwcWMySTJXRWt2Wms1YVZqbDNOMnRVVlRselFXcGlkalI2V2pCbk5HSXZUMG92Yld4TGNrczBaR2c0VTFsRFRqZDZZVGxxTW5SR2JEQTFObkZuYlRoTWIzVjVOR1ZTWkVGUFpXTnNZV3d4ZG05d2IxRTNMMWRaTDNOMGQycHlLMmd2T0hkMU1rUkNlR2N5VVN0dFVIRlNSVFZwTm5kME5YWmplVEZWUzJORVdGbEJWSGtyZGxsVlZHTnRhVTEzUVRRemVTOXJOVzkwUzFKWWVtTmhjblJ4VkZGMlNqWnFSVGx2YW5aSmRFMVNXRTkwYVhVeGFGaFlNV3BRWlZKSWMzaFFRek55YkdWdFRVRm1ZMWx1Y0V4Uk5UVTFZVXh4Y25GTVJESkRZM2hCYmxNcloxTllObmhWYUdNMmREVk5XREl2VTBzM2NrcE1iMUZzT1VKdE1HSm1TbGxXUTNVNFNVWlpkMGhzVFdaaVowTnVWR1o1TlZjd0x5OTJVR0pTT0U1dFRsbzBRa3RTVjA5UlVuSkJiR3BrZGtNeWRsVmlXWGRRY1d0SlJpOVNRMFIxYjBZMFlYTnhPVTFsZVhOUmVqTmxhekF2T0hwTmVrUmtSSGg2WlhWVFZua3lSblpYWm5Fd1ZtRjBUak55VDFaUVJsTjNVM0pYVTFwWWRrTjZlRUYxUWpFelNGaGxiMUJWVGtoTFIxSXlVWG96VGxadGVXcFNjRVpWV0RsUVFXWXlka2x1UW01T1dYSkdOalU1UlVwcGFsSjBaM0puYW5aM2FqVjBiM1JLVmtrMFpqSjBRMnQyT0N0bGMyMUxlVlo0U0VsQ2MyaEtUWEl4VDFvM1NTdEJaVFJwUjNrdk4yMVlRWGxYVGxReGRXOTFUaTlhTDFCcWFGTllOMXAzYmxBM2NWTnRVRlEwUVZoSE5DOVpXRUp5YlRobU9UTkNTVTVMUzBoSldHWTBVbGQwY25wbkwySm5jMHBTT1hObVIyWjZSRGh5ZEU1UVZGQmhXRXhWV1hSa2MzZGtlRkk1WjBGdlNsZDNUV3RNUTB4NkswczJXalJyUm10S2RqYzJTalp6V1hSMVJXdzNiRGN4VUNzd2EzRmtSazh6V1VoWGFXUjVRbTl5U0ZGMFRXUlFVMGQyY1ZGVFYycENkV0o2ZW14R1VUTnZUVFpwUmtoRWEzUlVaVGhhWWt0elR6ZGlTV2RsTVZaWlp5dGxiRk13YnpOMVRWaE5PVkZrTTA1cVVrVXhTeTlaWTFKbk5GRnNXbHBHWVhCTEsyMDFNV3BhVkZCMVZESkhaamh1VGxsT1NEQjNkejAuY1N5b3dvMTJXSUFhVDY4VXRWSU5fOEw2QkhMOXNQVXpkUXpaQWx3TVgzbkJmVmxaZlN3R05DREN4MmNNZkJJaXhYbnRSVmYweG5CY09CZDdiWDBzWEE="/>
}
